name: .NET Build and Deploy

on:
  push:
    branches:
      - master  
  pull_request:
    branches:
      - master 

jobs:
  build:
    runs-on: ubuntu-latest  

    steps:
    - name: Checkout code
      uses: actions/checkout@v2  

    - name: Setup .NET
      uses: actions/setup-dotnet@v2  
      with:
        dotnet-version: '7.0'  

    - name: Restore dependencies
      run: dotnet restore  

    - name: Build project
      run: dotnet build --configuration Release  

    - name: Run tests
      run: dotnet test --configuration Release  

    - name: Publish
      run: dotnet publish --configuration Release --output ./publish  

    - name: Deploy to Azure (optional)
      if: success() 
      run: |
        # Example of deploying to Azure
        az webapp deploy --resource-group <resource_group> --name <webapp_name> --src-path ./publish
